name: 'GitHub Actions Mirror'

on: [push, delete]

jobs:
   mirror_to_CODECHINA:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to CODE CHINA'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@codechina.csdn.net:xiongjiamu/jupyter-101.git
          ssh_private_key:
            ${{ secrets.CODECHINA }}
   mirror_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1
      - name: 'Mirror to CODE CHINA'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitlab.com:Miykael/jupyter-101.git
          ssh_private_key:
            ${{ secrets.CODECHINA }}